#!/bin/sh
make clean
make apogee_PPI.so
g++ -I/opt/apogee/include  test_apogee.cpp \
                        CameraIO_Linux.o CameraIO_LinuxPPI.o \
                        -o test_apogeeppi  -DAPOGEE_PPI \
                        -L/opt/apogee/lib -ltcl8.3 -lccd -lfitsTcl